name: Build npm and push to npm

on:
  release:
    types: [created]

jobs:
  publish-npm-global-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install depedencies
        run: npm ci

      - name: Build libraries
        run: npm run build

      - name: Publish to npm funixproductions-requests
        run: cd dist/funixproductions-requests && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

