name: Test build lib

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodejs 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install depedencies
        run: npm ci

      - name: Build
        run: npm run build
